language: node_js
sudo: false
addons:
  apt:
    packages:
    - python-demjson
install:
  - npm install
before_script:
  openssl aes-256-cbc -K $encrypted_dde8a6eeaa7c_key -iv $encrypted_dde8a6eeaa7c_iv -in config.json.enc -out config.json -d
script:
  - jsonlint data/imposm3_mapping.json
  - GLOBIGNORE="layers.yml:.travis.yml"
  - for style in *.yml; do
      jsonstyle="$(./node_modules/.bin/cartodb-yaml $style)" || exit 1;
      if [[ "$jsonstyle" == "{}" ]]; then echo "$style created an empty JSON file"; exit 1; fi
    done